name: Flutter Android Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Debug flutter env
        run: flutter doctor -v

      - name: Build APK
        run: flutter build apk --release

      - name: Check APK exists
        run: |
          if [ ! -f build/app/outputs/flutter-apk/app-release.apk ]; then
            echo "❌ APK not found!"
            exit 1
          else
            echo "✅ APK found"
          fi

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: zen-click-apk
          path: build/app/outputs/flutter-apk/app-release.apk
          compression-level: 0
